public enum TokenDesc {
	PARSER_ERROR, 				//0
	START_STATE, 				//1
	UNSIGNED_INTEGER, 			//2
	SIGNED_INTEGER, 			//3
	UNSIGNED_FLOAT, 			//4
	SIGNED_FLOAT, 				//5
	GLOBAL_VARIABLE_NAME, 		//6			//old: BIG_LETTERS_ONLY,
	FUNCTION_NAME, 				//7 		//old: BIG_FIRST_LETTER_SMALL_LETTERS, //BIG_FIRST_LETTER_BIG_LETTERS_SMALL_LETTERS,
	VARIABLE_NAME, 				//8
	PLUS_SIGN,  				//9
	MINUS_SIGN, 				//10
	MULTIPLICATION_SIGN, 		//11
	DIVISION_SIGN, 				//12
	MODULO_SIGN, 				//13	// %
	MATH_EQUALITY_SIGN, 		//14	// =
	LOGIC_EQUALITY_SIGN, 		//15	// ==
	LOGIC_INEQUALITY_SIGN,	 	//16	// !=
	LESSER_THAN_SIGN, 			//17	// <
	GREATER_THAN_SIGN, 			//18	// >
	LESSER_THAN_OR_EQUAL_SIGN,	//19	// <=
	GREATER_THAN_OR_EQUAL_SIGN, //20	// >=
	
	ASSIGNMENT_SIGN, 			//21	// :=
	SEMICOLON_SIGN, 			//22	// ;
	JAVA_SCRIPT_EQUALITY_SIGN, 	//23	// ===
	
	DOT1_STATE, 				// NIEAKCEPTUJACY 24
	DOT2_STATE,					// NIEAKCEPTUJACY 25
	EXCLAMATION_STATE, 			// NIEAKCEPTUJACY 26
	COLON_STATE, 				// NIEAKCEPTUJACY 27
}
